moddef::moddef!(
    flat(pub) mod {
        lr,
        omega_epsilon_xi,
        omega_epsilon,
        omega_zeta,
        omega,
        omega2_zeta,
        pi,
        pid,
        rc,
        rc2_sallen_key,
        rc2,
        rc2g_sallen_key,
        rc3_sallen_key,
        rc3g_sallen_key,
        rlc,
        tau,
        wah
    }
);